config/routes.rb
Rails.application.routes.draw do

  get 'supply_user_notifications/index'
  get 'notifications/index'
	root 'home#top'
	get 'about' => 'home#about'

  devise_for :demand_users, controllers: {
    sessions: 'demand_users/sessions',
    passwords: 'demand_users/passwords',
    registrations: 'demand_users/registrations'
  }
  devise_for :supply_users, controllers: {
    sessions: 'supply_users/sessions',
    passwords: 'supply_users/passwords',
    registrations: 'supply_users/registrations'
  }
  get 'demand_users/withdraw' => 'demand_users#withdraw'
  patch 'demand_users/out' => 'demand_users#out'
  resources :demand_users, only: [:show, :update] do
    scope module: 'supply_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'demand_users/demand_users/edit' => 'demand_users#edit'
  get 'supply_users/withdraw' => 'supply_users#withdraw'
  patch 'supply_users/out' => 'supply_users#out'
	resources :supply_users, only: [:show, :index, :update] do
    scope module: 'demand_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'supply_users/supply_users/edit' => 'supply_users#edit'
  get 'favorites' => 'favorites#index', as: :favorites
  resources :animals do
  	resources :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  resources :events
  resources :chats, only: [:create, :index]
  resources :demand_user_notifications, only: [:index]
  resources :supply_user_notifications, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :demand_user
	belongs_to :animal

  validates :demand_user_id, presence: true
  validates :animal_id, presence: true

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_demand_user!

def index
	@favorites = Favorite.where(demand_user_id: current_demand_user.id)
end

def create
  @animal = Animal.find(params[:animal_id])
  favorite = current_demand_user.favorites.new(animal_id: @animal.id)
  favorite.save
end

def destroy
  @animal = Animal.find(params[:animal_id])
  favorite = current_demand_user.favorites.find_by(animal_id: @animal.id)
  favorite.destroy
end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if @animal.favorited_by?(current_demand_user) %>
  <%= link_to animal_favorite_path(@animal,current_demand_user), method: :delete, remote: true do %>
    <span class="btn btn-danger">気になるリスト削除</span>
  <% end %>
<% else %>
  <%= link_to animal_favorites_path(@animal), method: :post, remote: true do %>
    <span class="btn btn-info">気になるリスト追加</span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @animal.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {animal: @animal}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @animal.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {animal: @animal}) %>");

app/views/favorites/index.html.erb
<div class="row">
	<h2 class="title-left"><span class="underbar">気になるリスト</span></h2>
	<div class="col-xs-12 text-center index-space">
		<div class="row">
			<% if @favorites.exists? %>
				<% @favorites.each do |favorite| %>
					<% animal = Animal.find_by(id: favorite.animal_id) %>
					<% if animal.sex == "オス" %>
						<div class="col-xs-3 animalmale hover">
							<div>
								<%= link_to animal_path(animal) do %>
									<%= attachment_image_tag animal, :image, format: 'jpeg', size:"230x230", class: "animal-image" %>
										<p><%= animal.name %></p>
										<p><%= animal.bleed.name %>/<%= animal.sex %>/<%= animal.age %></p>
								<% end %>
							</div>
						</div>
					<% else %>
						<div class="col-xs-3 animalfemale hover">
							<div>
								<%= link_to animal_path(animal) do %>
									<%= attachment_image_tag animal, :image, format: 'jpeg', size:"230x230", class: "animal-image" %>
										<p class="animalfont"><%= animal.name %></p>
										<p class="animalfont"><%= animal.bleed.name %>/<%= animal.sex %>/<%= animal.age %></p>
								<% end %>
							</div>
						</div>
					<% end %>
				<% end %>
			<% else %>
				<h3>[気になるリスト追加]ボタンを押すとココに表示されます</h3>
			<% end %>
		</div>
	</div>
</div>