config/routes.rb
Rails.application.routes.draw do

  get 'supply_user_notifications/index'
  get 'notifications/index'
	root 'home#top'
	get 'about' => 'home#about'

  devise_for :demand_users, controllers: {
    sessions: 'demand_users/sessions',
    passwords: 'demand_users/passwords',
    registrations: 'demand_users/registrations'
  }
  devise_for :supply_users, controllers: {
    sessions: 'supply_users/sessions',
    passwords: 'supply_users/passwords',
    registrations: 'supply_users/registrations'
  }
  get 'demand_users/withdraw' => 'demand_users#withdraw'
  patch 'demand_users/out' => 'demand_users#out'
  resources :demand_users, only: [:show, :update] do
    scope module: 'supply_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'demand_users/demand_users/edit' => 'demand_users#edit'
  get 'supply_users/withdraw' => 'supply_users#withdraw'
  patch 'supply_users/out' => 'supply_users#out'
	resources :supply_users, only: [:show, :index, :update] do
    scope module: 'demand_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'supply_users/supply_users/edit' => 'supply_users#edit'
  get 'favorites' => 'favorites#index', as: :favorites
  resources :animals do
  	resources :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  resources :events
  resources :chats, only: [:create, :index]
  resources :demand_user_notifications, only: [:index]
  resources :supply_user_notifications, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	@animals = Animal.all.order(created_at: :desc)
  	@events = Event.all.order(created_at: :desc)
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="about">
	<p class="touch">↓タッチしてください↓</p>
	<div class="about_FosPa">
		<div>
			<span class="underbar">FosPaとは！？</span>
		</div>
		<p class="about_comment">
			犬猫を家族として迎えたい方、そのもらい手を探している方を結ぶサイトです。<br>
			近年、ペットブームの影響による飼育数の増加から飼育放棄される動物の<br>
			数も増加しています。その数は、数十年前より大きく減少はしていますが、<br>
			「環境省の犬・猫の殺処分の統計」の平成３０年のデータによると<br>
			年間約３万８千頭に昇り、一日あたり１００頭近くの犬猫が殺処分されています。<br>
			そこで殺処分ゼロをにしたいという願いからこのサイトを作成しました。<br>
			＊ポートフォリオ用に制作したサイトになります＊
		</p>
	</div>
</div>

app/views/home/top.html.erb
<div class="row">
	<div class="text-center">
		<h2><span class="underbar">FosPaへようこそ！</span></h2>
		<p>FosPa(フォスパ)は犬猫を家族として迎えたい方、もらい手を探している方を結ぶサイトです。</p>
	</div>
	<div class="text-center">
		<h3>どちらをお探しですか？</h3>
		<% @genres.each do |genre| %>
    	<%= link_to genre_path(genre), class: "choice hover" do %>
					<i class="fas fa-paw"><%= genre.name %></i>
     	<% end %>
    <% end %>
	</div>
	<div class="shintyaku visible-lg-block">
		<h3 class="title-left"><span class="underbar">新着情報</span></h3>
		<div class="bxslider">
			<% @animals.each do |animal| %>
				<% if animal.sex == "オス" %>
					<div class="slidecontent_an hover">
						<div class="animalmale_top">
							<%= link_to animal_path(animal) do %>
								<%= attachment_image_tag animal, :image, format: 'jpeg', size:"200x200", fallback: "fospa_no_image.png", class: "animal-image" %>
								<p><%= animal.name %></p>
							<% end %>
						</div>
					</div>
				<% else %>
					<div class="slidecontent_an hover">
						<div class="animalfemale_top">
							<%= link_to animal_path(animal) do %>
								<%= attachment_image_tag animal, :image, format: 'jpeg', size:"200x200", fallback: "fospa_no_image.png", class: "animal-image" %>
									<p class="animalfont"><%= animal.name %></p>
							<% end %>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="shintyaku visible-lg-block">
		<h3 class="title-left"><span class="underbar">新着イベント</span></h3>
		<div class="bxslider">
			<% @events.each do |event| %>
				<div class="slidecontent_ev hover">
					<div class="posted_top">
						<%= link_to event_path(event) do %>
							<%= attachment_image_tag event, :image, format: 'jpeg', size:"190x190" %>
							<p><span class="index-name"><%= event.name %></span></p>
							<p><%= event.day.strftime("%Y/%m/%d") %></p>
							<p><%= event.prefecture %></p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>