config/routes.rb
Rails.application.routes.draw do

  get 'supply_user_notifications/index'
  get 'notifications/index'
	root 'home#top'
	get 'about' => 'home#about'

  devise_for :demand_users, controllers: {
    sessions: 'demand_users/sessions',
    passwords: 'demand_users/passwords',
    registrations: 'demand_users/registrations'
  }
  devise_for :supply_users, controllers: {
    sessions: 'supply_users/sessions',
    passwords: 'supply_users/passwords',
    registrations: 'supply_users/registrations'
  }
  get 'demand_users/withdraw' => 'demand_users#withdraw'
  patch 'demand_users/out' => 'demand_users#out'
  resources :demand_users, only: [:show, :update] do
    scope module: 'supply_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'demand_users/demand_users/edit' => 'demand_users#edit'
  get 'supply_users/withdraw' => 'supply_users#withdraw'
  patch 'supply_users/out' => 'supply_users#out'
	resources :supply_users, only: [:show, :index, :update] do
    scope module: 'demand_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'supply_users/supply_users/edit' => 'supply_users#edit'
  get 'favorites' => 'favorites#index', as: :favorites
  resources :animals do
  	resources :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  resources :events
  resources :chats, only: [:create, :index]
  resources :demand_user_notifications, only: [:index]
  resources :supply_user_notifications, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord

  attr_accessor :dog_bleed_id, :cat_bleed_id

  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  belongs_to :bleed
  belongs_to :supply_user

  enum sex: {オス: 0, メス: 1}
  enum age: {"1歳未満": 0, "1~3歳未満": 1, "3~5歳未満": 2, "5~7歳未満": 3, "7歳以上": 4}

  validates :supply_user_id, presence: true
  validates :name, presence: true
  validates :sex, presence: true
  validates :age, presence: true
  validates :content, presence: true

  attachment :image

  #検索の記述　ここから----------------
  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
      .sex_is(search_params[:sex])
      .age_is(search_params[:age])
      .dog_bleed_id_is(search_params[:dog_bleed_id])
      .cat_bleed_id_is(search_params[:cat_bleed_id])
  end
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :sex_is, -> (sex) { where(sex: sex) if sex.present? }
  scope :age_is, -> (age) { where(age: age) if age.present? }
  scope :dog_bleed_id_is, -> (bleed_id) { where(bleed_id: bleed_id) if bleed_id.present? }
  scope :cat_bleed_id_is, -> (bleed_id) { where(bleed_id: bleed_id) if bleed_id.present? }
  #ここまで----------------------------

  def favorited_by?(demand_user)
    favorites.where(demand_user_id: demand_user.id).exists?
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  before_action :authenticate_supply_user!, only: [:new, :create, :edit, :update, :destroy]

  def show
  	@animal = Animal.find(params[:id])
  	@genre = Genre.find(@animal.bleed.genre_id)
  end

  def index
    @search_params = animal_search_params
    @bleed_dog = Bleed.where(genre_id: 1)
    @bleed_cat = Bleed.where(genre_id: 2)
    if current_supply_user
  	  @animals = current_supply_user.animals.search(@search_params)
                                            .includes(:bleed)
                                            .order(created_at: :desc)
                                            .page(params[:page])
    else
      @animals = Animal.search(@search_params)
                       .includes(:bleed)
                       .order(created_at: :desc)
                       .page(params[:page])
    end
  end

  def new
  	@animal = Animal.new
  	@bleed_dog = Bleed.where(genre_id: 1)
  	@bleed_cat = Bleed.where(genre_id: 2)
  end

  def create
  	@animal = Animal.new(animal_params)
    # params[:genre_radio] が 1
    params[:animal][:dog_bleed_id]
    # @animal の bleed_id に params[:animal][:dog_bleed_id] を代入
    if params[:genre_radio].to_i == 1
      @animal.bleed_id = params[:animal][:dog_bleed_id]
    # params[:genre_radio] が 2
    elsif params[:genre_radio].to_i == 2
    # @animal の bleed_id に params[:animal][:cat_bleed_id] を代入
      @animal.bleed_id = params[:animal][:cat_bleed_id]
    end

  	@animal.supply_user_id = current_supply_user.id
  	@bleed_dog = Bleed.where(genre_id: 1)
  	@bleed_cat = Bleed.where(genre_id: 2)
  	if @animal.save
      tags = Vision.get_image_data(@animal.image_id)
      tags.each do |tag|
        @animal.tags.create(name: tag)
      end
  		flash[:notice] = "募集完了しました。"
  		redirect_to animal_path(@animal)
  	else
  		render :new
  	end
  end

  def edit
    @animal = Animal.find(params[:id])
    @bleed_dog = Bleed.where(genre_id: 1)
    @bleed_cat = Bleed.where(genre_id: 2)
  end

  def update
    @animal = Animal.find(params[:id])
    # params[:genre_radio] が 1
    params[:animal][:dog_bleed_id]
    # @animal の bleed_id に params[:animal][:dog_bleed_id] を代入
    if params[:genre_radio].to_i == 1
      @animal.bleed_id = params[:animal][:dog_bleed_id]
    # params[:genre_radio] が 2
    elsif params[:genre_radio].to_i == 2
    # @animal の bleed_id に params[:animal][:cat_bleed_id] を代入
      @animal.bleed_id = params[:animal][:cat_bleed_id]
    end
    @animal.supply_user_id = current_supply_user.id
    @bleed_dog = Bleed.where(genre_id: 1)
    @bleed_cat = Bleed.where(genre_id: 2)
    if @animal.update(animal_params)
      flash[:notice] = "編集完了しました。"
      redirect_to animal_path(@animal)
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    if @animal.destroy
      flash[:notice] = "募集を削除しました。"
      redirect_to animals_path
    else
      render :show
    end
  end

  private

  def animal_params
  	params.require(:animal).permit(:supply_user_id, :image, :name, :sex, :age, :content, :animal_status)
  end

  def animal_search_params
    params.fetch(:search, {}).permit(:name, :sex, :age, :dog_bleed_id, :cat_bleed_id)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal_form.html.erb
<div class="row form-group">
  <div class="col-md-4 col-md-offset-1 col-xs-6">
    <label class="control-label">イメージ画像</label>
    <div>
      <%= attachment_image_tag animal, :image, format: 'jpeg', size:"300x300", fallback: "fospa_no_image.png", class: "image animal-image" %>
    </div>
    <%= f.attachment_field :image, autocomplete: "image_id", id:"image" %>
  </div>
  <div class="col-md-7 col-xs-6">
    <div class="row form-space">
      <div class="col-md-3 col-xs-5">
        <label class="control-label">名前</label>
        <%= f.text_field :name, class: "form-control", placeholder: "ポチ" %>
      </div>
    </div>
    <div class="row form-space">
      <div class="col-md-2 col-xs-4">
        <label class="control-label">性別</label>
        <%= f.select :sex, Animal.sexes.keys, {}, class: "form-control" %>
      </div>
      <div class="col-md-3 col-xs-6">
        <label class="control-label">年齢</label>
        <%= f.select :age, Animal.ages.keys, {}, class: "form-control" %>
      </div>
    </div>
    <div class="row form-space">
      <div class="col-xs-12">
        <label class="control-label">種類 <span class="explanation">(犬猫いずれかを選択,決定後に種類を選択)</span></label>
        <div class="row">
          <label class="col-md-2 col-xs-4"><input type="radio" name="genre_radio" value="1" checked="checked"> 犬</label>
          <label class="col-md-2 col-xs-4"><input type="radio" name="genre_radio" value="2"> 猫</label>
          <%= button_tag '決定', type: 'button', id:"kettei" %>
        </div>
      </div>
    </div>
    <div class="row form-space">
      <div class="col-md-5 col-xs-9">
        <div class="dog_select">
          <%= f.collection_select :dog_bleed_id, bleed_dog, :id, :name, {}, class: "form-control" %>
        </div>
        <div class="cat_select">
          <%= f.collection_select :cat_bleed_id, bleed_cat, :id, :name, {}, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row form-space">
      <div class="col-md-9 col-xs-11">
        <label class="control-label">紹介文</label>
        <%= f.text_area :content, class: "form-control", placeholder: "紹介文を入力", rows:5 %>
      </div>
    </div>
  </div>
</div>

app/views/animals/_animals.html.erb
<% animals.each do |animal| %>
	<% if animal.sex == "オス" %>
		<div class="col-md-3 col-xs-6 animalmale hover">
			<div>
				<%= link_to animal_path(animal) do %>
					<%= attachment_image_tag animal, :image, format: 'jpeg', size:"230x230", fallback: "fospa_no_image.png", class: "animal-image" %>
					<p><%= animal.name %></p>
					<p><%= animal.bleed.name %>/<%= animal.sex %>/<%= animal.age %></p>
				<% end %>
			</div>
		</div>
	<% else %>
		<div class="col-md-3 col-xs-6 animalfemale hover">
			<div>
				<%= link_to animal_path(animal) do %>
					<%= attachment_image_tag animal, :image, format: 'jpeg', size:"230x230", class: "animal-image" %>
						<p class="animalfont"><%= animal.name %></p>
						<p class="animalfont"><%= animal.bleed.name %>/<%= animal.sex %>/<%= animal.age %></p>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/animals/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="title-left"><span class="underbar">編集フォーム</span></h2>
  </div>
</div>
<%= form_for(@animal, url: animal_path) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <%= render 'animals/animal_form', f: f, animal: @animal, bleed_dog: @bleed_dog, bleed_cat: @bleed_cat %>
  <div class="row form-space">
    <div class="col-md-3 col-md-offset-5 col-xs-3 col-xs-offset-6">
      <%= f.submit "編集完了", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/animals/index.html.erb
<div class="row">
	<% unless current_supply_user %>
		<h2 class="title-left"><span class="underbar">犬猫詳細検索</span></h2>
	<% else %>
		<h2 class="title-left"><span class="underbar">里親募集履歴</span></h2>
	<% end %>
	<%= form_with(scope: :search, url: animals_path, method: :get, local: true) do |f| %>
	  <div class="row form-group">
	    <div class="col-xs-10 col-xs-offset-2">
	      <div class="row form-space">
	        <div class="col-md-3 col-xs-4">
	          <label class="control-label">名前</label>
	          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "ポチ", value: @search_params[:name] %>
	        </div>
	      </div>
	      <div class="row form-space">
	        <div class="col-md-3 col-xs-4">
	          <label class="control-label">性別</label>
	          <%= f.select :sex, Animal.sexes.keys, class: "form-control", prompt:"---選択して下さい---", value: @search_params[:sex] %>
	        </div>
	        <div class="col-md-3 col-xs-4">
	          <label class="control-label">年齢</label>
	          <%= f.select :age, Animal.ages.keys, class: "form-control", prompt:"---選択して下さい---", value: @search_params[:age] %>
	        </div>
	      </div>
	      <div class="row form-space">
	        <div class="col-xs-12">
	          <label class="control-label">種類 <span class="explanation">(犬猫いずれかを選択,決定後に種類を選択)</span></label>
	          <div class="row">
	            <label class="col-md-2 col-xs-2"><input type="radio" name="genre_radio" value="1"> 犬</label>
	            <label class="col-md-2 col-xs-2"><input type="radio" name="genre_radio" value="2"> 猫</label>
	            <div class="col-md-2 col-xs-3">
	            	<%= button_tag '決定', type: 'button', id:"kettei" %>
	         		</div>
	            <div class="col-md-2 col-xs-2">
			          <%= f.submit "検索", class: "btn btn-info" %>
			        </div>
	          </div>
	        </div>
	      </div>
	      <div class="row form-space">
	        <div class="col-xs-4">
	          <div class="dog_select">
	            <%= f.collection_select :dog_bleed_id, @bleed_dog, :id, :name, class: "form-control", prompt:"-------選択して下さい-------", value: @search_params[:bleed_id] %>
	          </div>
	          <div class="cat_select">
	            <%= f.collection_select :cat_bleed_id, @bleed_cat, :id, :name, class: "form-control", prompt:"------選択して下さい------", value: @search_params[:bleed_id] %>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
	<% end %>
	<div class="col-xs-12 text-center index-space">
		<div class="row">
			<% if @animals.exists? %>
				<%= render 'animals/animals', animals: @animals %>
			<% else %>
				<% if current_supply_user %>
					<h3>現在、募集していません</h3>
				<% else %>
					<h3>募集がありません</h3>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/animals/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="title-left"><span class="underbar">募集フォーム</span></h2>
  </div>
</div>
<%= form_for(@animal) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <%= render 'animals/animal_form', f: f, animal: @animal, bleed_dog: @bleed_dog, bleed_cat: @bleed_cat %>
  <div class="row form-space">
    <div class="col-md-3 col-md-offset-5 col-xs-3 col-xs-offset-6">
      <%= f.submit "募集する", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/animals/show.html.erb
<div class="row relative">
  <h2 class="title-left"><span class="underbar"><%= @animal.name %> のプロフィール</span></h2>
  <div class="supply-link-position">
  	<% if current_supply_user && current_supply_user == @animal.supply_user %>
  		<%= link_to "編集", edit_animal_path, class: "btn btn-default" %>
  		<%= link_to "削除", animal_path(@animal), method: :delete, class: "btn btn-danger", data: {confirm: "削除しますか？"} %>
  	<% end %>
  </div>
</div>
<div class="row index-space">
	<div class="col-md-4 col-md-offset-1 col-xs-6">
		<%= attachment_image_tag @animal, :image, format: 'jpeg', size: '250x250', fallback: "fospa_no_image.png", class: "animal-image" %>
		<div class="text-right">
			<% @animal.tags.each do |tag| %>
	      <span class="animal_tag"><%= tag.name %></span>
	    <% end %>
  	</div>
	</div>
	<div class="col-md-7 col-xs-6">
		<table class="table table-striped table-bordered user-table">
			<tbody>
				<tr>
					<td class="category">名前</td>
					<td class="infomation">
						<%= @animal.name %>
						<!-- お気に入りリスト -->
						<% if current_demand_user %>
							<span id="favorites_buttons_<%= @animal.id %>">
								<%= render partial: 'favorites/favorite', locals: {animal: @animal} %>
							</span>
						<% end %>
						<!-- ここまで -->
					</td>
				</tr>
				<tr>
					<td class="category">種類</td>
					<td class="infomation"><%= @animal.bleed.name %></td>
				</tr>
				<tr>
					<td class="category">性別</td>
					<td class="infomation"><%= @animal.sex %></td>
				</tr>
				<tr>
					<td class="category">年齢</td>
					<td class="infomation"><%= @animal.age %></td>
				</tr>
				<tr>
					<td class="category">紹介文</td>
					<td class="infomation"><%= simple_format(@animal.content) %></td>
				</tr>
				<tr>
					<td class="category">募集元</td>
					<td class="infomation">
						<%= @animal.supply_user.name %> さん
						<% if current_demand_user %>
							<%= link_to "お問い合わせ", supply_user_chats_path(@animal.supply_user_id), class: "btn btn-default" %>
						<% end %>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<% if current_supply_user %>
				<div class="col-xs-3 col-xs-offset-9">
					<%= link_to "一覧へ", animals_path %>
					<span>
					| <%= link_to "戻る", :back %>
		  		</span>
		  	</div>
	  	<% else %>
				<div class="col-xs-2 col-xs-offset-10">
					<%= link_to "戻る", :back %>
	  		</div>
			<% end %>
		</div>
	</div>
</div>