config/routes.rb
Rails.application.routes.draw do

  get 'supply_user_notifications/index'
  get 'notifications/index'
	root 'home#top'
	get 'about' => 'home#about'

  devise_for :demand_users, controllers: {
    sessions: 'demand_users/sessions',
    passwords: 'demand_users/passwords',
    registrations: 'demand_users/registrations'
  }
  devise_for :supply_users, controllers: {
    sessions: 'supply_users/sessions',
    passwords: 'supply_users/passwords',
    registrations: 'supply_users/registrations'
  }
  get 'demand_users/withdraw' => 'demand_users#withdraw'
  patch 'demand_users/out' => 'demand_users#out'
  resources :demand_users, only: [:show, :update] do
    scope module: 'supply_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'demand_users/demand_users/edit' => 'demand_users#edit'
  get 'supply_users/withdraw' => 'supply_users#withdraw'
  patch 'supply_users/out' => 'supply_users#out'
	resources :supply_users, only: [:show, :index, :update] do
    scope module: 'demand_users' do
      get 'chats' => 'chats#new'
    end
  end
  get 'supply_users/supply_users/edit' => 'supply_users#edit'
  get 'favorites' => 'favorites#index', as: :favorites
  resources :animals do
  	resources :favorites, only: [:create, :destroy]
  end
  resources :genres, only: [:show]
  resources :events
  resources :chats, only: [:create, :index]
  resources :demand_user_notifications, only: [:index]
  resources :supply_user_notifications, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/supply_user.rb
class SupplyUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :chats, dependent: :destroy
  has_many :animals, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :demand_user_notifications, foreign_key: 'sender_id', dependent: :destroy
  has_many :supply_user_notifications, foreign_key: 'receiver_id', dependent: :destroy

  enum is_deleted: { 有効: false, 退会済み: true }

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

def active_for_authentication?
  super && (self.is_deleted === "有効")
end

end

app/controllers/supply_users/chats_controller.rb
class SupplyUsers::ChatsController < ApplicationController
	def new
		@chat = Chat.new
		@chats = Chat.where(demand_user_id: params[:demand_user_id], supply_user_id: current_supply_user.id)
		@demand_user = DemandUser.find(params[:demand_user_id])
		render 'chats/new'
	end
end

app/controllers/supply_users/confirmations_controller.rb
# frozen_string_literal: true

class SupplyUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/supply_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class SupplyUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/supply_users/passwords_controller.rb
# frozen_string_literal: true

class SupplyUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/supply_users/registrations_controller.rb
# frozen_string_literal: true

class SupplyUsers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :postal_code, :address, :phone, :image, :is_deleted])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    supply_users_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/supply_users/sessions_controller.rb
# frozen_string_literal: true

class SupplyUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    supply_users_path
  end

  def after_sign_out_path_for(resource)
    new_supply_user_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/supply_users/unlocks_controller.rb
# frozen_string_literal: true

class SupplyUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/supply_users_controller.rb
class SupplyUsersController < ApplicationController

  before_action :authenticate_supply_user!

  def show
  end

  def edit
  	@supply_user = SupplyUser.find(current_supply_user.id)
  end

  def update
  	@supply_user = SupplyUser.find(current_supply_user.id)
  	if @supply_user.update(supply_user_params)
      flash[:notice] = "会員情報を更新しました。"
  		redirect_to supply_user_path(current_supply_user)
  	else
  		render :edit
  	end
  end

  def withdraw
  end

  def out
    current_supply_user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def supply_user_params
  	params.require(:supply_user).permit(:image, :name, :name_kana, :email, :postal_code, :address, :phone)
  end

end

app/helpers/supply_users/chats_helper.rb
module SupplyUsers::ChatsHelper
end

app/helpers/supply_users_helper.rb
module SupplyUsersHelper
end

app/views/supply_users/edit.html.erb
<div class="row">
  <div class="col-xs-4">
    <h2><span class="underbar">会員編集</span></h2>
  </div>
</div>
<%= form_for(@supply_user, url: supply_user_path(current_supply_user)) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row form-group">
    <div class="col-md-4 col-md-offset-1 col-xs-6">
      <label class="control-label">イメージ画像</label>
      <div>
        <%= attachment_image_tag @supply_user, :image, format: 'jpeg', size:"300x300", fallback: "fospa_no_image.png", class: "image" %>
      </div>
      <%= f.attachment_field :image, autocomplete: "image_id", id:"image" %>
    </div>
    <div class="col-md-7 col-xs-6">
      <div class="row form-space">
        <div class="col-md-9 col-xs-11">
          <label class="control-label">名前または法人名</label>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "里親太郎" %>
        </div>
      </div>
      <div class="row form-space">
        <div class="col-md-9 col-xs-11">
          <label class="control-label">フリガナ</label>
          <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana", class: "form-control", placeholder: "サトオヤタロウ" %>
        </div>
      </div>
      <div class="row form-space">
        <div class="col-md-6 col-xs-11">
          <label class="control-label">メールアドレス</label>
          <%= f.email_field :email, autocomplete: "email", class: "form-control", placeholder: "〇〇〇〇＠〇〇.〇〇" %>
        </div>
      </div>
      <div class="row form-space">
        <div class="col-xs-6">
          <label class="control-label">郵便番号(ハイフンなし)</label>
          <%= f.text_field :postal_code, autocomplete: "postal_code", id: "user_postal_code", class: "form-control", placeholder: "1234567" %>
        </div>
      </div>
      <div class="row form-space">
        <div class="col-md-9 col-xs-11">
          <label class="control-label">住所または所在地</label>
          <%= f.text_field :address, autocomplete: "address", id: "user_address", class: "form-control", placeholder: "東京都千代田区霞ヶ関〇-〇-〇" %>
        </div>
      </div>
      <div class="row form-space">
        <div class="col-xs-6">
          <label class="control-label">電話番号(ハイフンなし)</label>
          <%= f.text_field :phone, autocomplete: "phone", class: "form-control", placeholder: "12345678910" %>
        </div>
      </div>
      <div class="row form-space">
        <div class="col-xs-12">
          <%= f.submit "編集完了", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/supply_users/index.html.erb
<div class="row">
	<div class="text-center">
		<h2><span class="underbar">FosPaへようこそ！</span></h2>
		<p>FosPa(フォスパ)は犬猫を家族として迎えたい方、もらい手を探している方を結ぶサイトです。</p>
	</div>
	<div class="text-center">
		<h3>どちらご希望ですか？</h3>
		<div>
    	<%= link_to new_animal_path, class: "choice_left hover" do %>
				<p>里親募集</p>
     	<% end %>
     	<%= link_to new_event_path, class: "choice_right hover" do %>
				<p>イベント告知</p>
     	<% end %>
    </div>
    <div class="index-space">
    	<%= link_to animals_path, class: "choice_left hover" do %>
				<p>里親募集履歴</p>
     	<% end %>
     	<%= link_to events_path, class: "choice_right hover" do %>
				<p>イベント投稿履歴</p>
     	<% end %>
    </div>
	</div>
</div>

app/views/supply_users/show.html.erb
<div class="row relative">
  <div class="col-xs-4">
    <h2><span class="underbar">会員情報</span></h2>
  </div>
  <% if current_supply_user.id != 1 %>
	  <div class="supply-link-position">
	  	<%= link_to "編集", supply_users_supply_users_edit_path, class: "btn btn-default" %>
	  </div>
  <% end %>
</div>
<div class="row index-space">
	<div class="col-md-3 col-md-offset-1 col-xs-4">
		<%= attachment_image_tag current_supply_user, :image, format: 'jpeg', size: '250x250', fallback: "fospa_no_image.png" %>
	</div>
	<div class="col-md-8 col-xs-8">
		<table class="table table-striped table-bordered user-table">
			<tbody>
				<tr>
					<td class="category">氏名または法人名</td>
					<td class="infomation"><%= current_supply_user.name %></td>
				</tr>
				<tr>
					<td class="category">氏名または法人名(フリガナ)</td>
					<td class="infomation"><%= current_supply_user.name_kana %></td>
				</tr>
				<tr>
					<td class="category">メールアドレス</td>
					<td class="infomation"><%= current_supply_user.email %></td>
				</tr>
				<tr>
					<td class="category">郵便番号</td>
					<td class="infomation"><%= current_supply_user.postal_code %></td>
				</tr>
				<tr>
					<td class="category">住所または所在地</td>
					<td class="infomation"><%= current_supply_user.address %></td>
				</tr>
				<tr>
					<td class="category">電話番号</td>
					<td class="infomation"><%= current_supply_user.phone %></td>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<div class="col-xs-2 col-xs-offset-9">
				<%= link_to "退会する", supply_users_withdraw_path, class: "btn btn-danger" %>
			</div>
		</div>
	</div>
</div>

app/views/supply_users/withdraw.html.erb
<div class="text-center">
	<div>
		<h2><b>本当に退会しますか？</b></h2>
	</div>
</div>
<div class="text-center">
	<div>
		<P>退会すると、会員情報や各履歴の閲覧、</P>
		<p>里親募集やイベント告知ができなくなります。</p>
		<p>退会する場合は、「退会する」をクリックしてください。</p>
	</div>
</div>
<div class="text-center">
	<div class="inline">
		<%= link_to "退会しない", supply_user_path(current_supply_user), class: "btn btn-info hover" %>
	</div>
	<% if current_supply_user.id != 1 %>
		<div class="inline">
			<%= link_to "退会する", supply_users_out_path, method: :patch, class: "btn btn-danger hover", data: {confirm: "本当によろしいですか？"} %>
		</div>
	<% end %>
</div>